version: '3.9'

services:
  app:
    container_name: app
    environment:
      - NODE_ENV=developement
      - PORT=3000
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    ports:
      - 4000:3000
    command: npm run dev
